# Generated by Django 6.0.4 on 2026-04-16 17:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'db_table': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('EN_COURS', 'En cours'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'commande',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id_livreur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_livreur', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('est_disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Livreur',
                'verbose_name_plural': 'Livreurs',
                'db_table': 'livreur',
            },
        ),
        migrations.CreateModel(
            name='Materiau',
            fields=[
                ('id_materiau', models.AutoField(primary_key=True, serialize=False)),
                ('nom_materiau', models.CharField(max_length=100, unique=True)),
                ('quantite_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seuil_alerte', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unite', models.CharField(choices=[('METRE', 'Mètre'), ('PIECE', 'Pièce'), ('BOUTON', 'Bouton'), ('FERMETURE', 'Fermeture Éclair'), ('BOBINE', 'Bobine de fil')], default='METRE', max_length=20)),
            ],
            options={
                'verbose_name': 'Matériau',
                'verbose_name_plural': 'Matériaux',
                'db_table': 'materiau',
            },
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id_mesure', models.AutoField(primary_key=True, serialize=False)),
                ('mesures', models.JSONField(help_text="Format JSON : {'poitrine': 90, 'taille': 70, 'hanches': 95}")),
                ('date_prise', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mesure',
                'verbose_name_plural': 'Mesures',
                'db_table': 'mesure',
                'ordering': ['-date_prise'],
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id_livraison', models.AutoField(primary_key=True, serialize=False)),
                ('adresse_client', models.TextField()),
                ('date_livraison', models.DateField(blank=True, null=True)),
                ('status_livraison', models.CharField(choices=[('EN_PREPARATION', 'En préparation'), ('EN_ROUTE', 'En route'), ('LIVREE', 'Livrée')], default='EN_PREPARATION', max_length=20)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='Sew.commande')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='Sew.livreur')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'db_table': 'livraison',
            },
        ),
        migrations.CreateModel(
            name='Consomme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_necessaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('materiau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sew.materiau')),
            ],
            options={
                'verbose_name': 'Consommation matière',
                'verbose_name_plural': 'Consommations matières',
                'db_table': 'consomme',
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='mesures_utilisees',
            field=models.ForeignKey(blank=True, help_text='Mesures spécifiques pour cette commande', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sew.mesure'),
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id_modele', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delai', models.IntegerField(help_text='Délai de confection en jours')),
                ('image', models.ImageField(blank=True, null=True, upload_to='modeles/')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modeles', to='Sew.categorie')),
                ('materiaux', models.ManyToManyField(related_name='modeles', through='Sew.Consomme', to='Sew.materiau')),
            ],
            options={
                'verbose_name': 'Modèle',
                'verbose_name_plural': 'Modèles',
                'db_table': 'modele',
            },
        ),
        migrations.AddField(
            model_name='consomme',
            name='modele',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sew.modele'),
        ),
        migrations.AddField(
            model_name='commande',
            name='modele',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='Sew.modele'),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id_paiement', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('ACOMPTE', 'Acompte'), ('SOLDE', 'Solde'), ('TOTAL', 'Total')], default='ACOMPTE', max_length=20)),
                ('methode', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('CARTE', 'Carte bancaire')], default='ESPECES', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='Sew.commande')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'paiement',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('CLIENT', 'Client'), ('COUTURIER', 'Couturier'), ('LIVREUR', 'Livreur')], default='CLIENT', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'utilisateur',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notif', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('type_message', models.CharField(choices=[('PROMO', 'Promotion'), ('ALERTE', 'Alerte'), ('STATUT', 'Statut commande'), ('INFO', 'Information')], default='INFO', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('est_lue', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='mesure',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id_message', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('est_lu', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'message',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='consomme',
            unique_together={('modele', 'materiau')},
        ),
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sew.modele')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'db_table': 'favoris',
                'unique_together': {('utilisateur', 'modele')},
            },
        ),
    ]
