# Generated by Django 6.0.4 on 2026-04-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sew', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoris',
            name='id',
        ),
        migrations.AddField(
            model_name='favoris',
            name='id_favori',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mesure',
            name='mesures',
            field=models.JSONField(help_text="Format JSON : {'poitrine': 90, 'longueur': 120, 'taille': 70, 'hanches': 95}"),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('COUTURIER', 'Couturier'), ('LIVREUR', 'Livreur')], default='CLIENT', max_length=20),
        ),
    ]
