# Generated by Django 6.0.4 on 2026-06-13 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sew', '0002_remove_favoris_id_favoris_id_favori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='utilisateur',
            field=models.OneToOneField(blank=True, help_text='Compte applicatif associé à ce livreur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_livreur', to=settings.AUTH_USER_MODEL),
        ),
    ]
