# Generated by Django 6.0.4 on 2026-06-13 14:40

import Sew.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sew', '0003_livreur_lien_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesure',
            name='mesures',
            field=models.JSONField(help_text='Objet JSON avec au minimum : poitrine, taille, hanches, longueur (en cm). Exemple : {"poitrine": 90, "taille": 70, "hanches": 95, "longueur": 120}', validators=[Sew.models.valider_mesures]),
        ),
    ]
