# Generated by Django 6.0.4 on 2026-06-13 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sew', '0006_migrer_role_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='couturier',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'COUTURIER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Couturier assigné'),
        ),
    ]
