# Generated by Django 6.0.4 on 2026-06-13 15:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sew', '0007_commande_couturier'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée de stock'), ('SORTIE', 'Sortie de stock'), ('AJUSTEMENT', 'Ajustement inventaire')], max_length=20)),
                ('quantite', models.DecimalField(decimal_places=2, help_text='Quantité ajoutée / retirée, ou nouvelle valeur absolue pour AJUSTEMENT', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, help_text="N° de bon de commande fournisseur, ticket d'inventaire, etc.", max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('commande', models.ForeignKey(blank=True, help_text='Renseigné automatiquement pour les sorties liées à une commande', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='Sew.commande')),
                ('materiau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='Sew.materiau')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'db_table': 'mouvement_stock',
                'ordering': ['-date'],
            },
        ),
    ]
