# Generated by Django 6.0.4 on 2026-06-14 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sew', '0009_avis_notation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type_remise', models.CharField(choices=[('POURCENTAGE', 'Pourcentage (%)'), ('FIXE', 'Montant fixe (FCFA)')], max_length=20)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valide_du', models.DateTimeField(blank=True, null=True)),
                ('valide_jusqu_au', models.DateTimeField(blank=True, null=True)),
                ('usage_max', models.PositiveIntegerField(blank=True, help_text='Vide = illimité', null=True)),
                ('nb_utilisations', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Code promo',
                'verbose_name_plural': 'Codes promo',
                'db_table': 'code_promo',
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='remise_appliquee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='code_promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='Sew.codepromo'),
        ),
    ]
