# Generated by Django 6.0.4 on 2026-06-14 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sew', '0010_code_promo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id_devis', models.AutoField(primary_key=True, serialize=False)),
                ('notes_client', models.TextField(blank=True)),
                ('prix_propose', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delai_propose', models.PositiveIntegerField(blank=True, help_text='Délai en jours', null=True)),
                ('commentaire_couturier', models.TextField(blank=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('DEMANDE', 'Demande reçue'), ('PROPOSE', 'Devis proposé'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé')], default='DEMANDE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to=settings.AUTH_USER_MODEL)),
                ('commande', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_source', to='Sew.commande')),
                ('mesures', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sew.mesure')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis', to='Sew.modele')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'db_table': 'devis',
                'ordering': ['-date_creation'],
            },
        ),
    ]
