# Generated by Django 6.0.4 on 2026-06-15 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sew', '0012_devis_annule_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreAtelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acompte_pourcentage', models.PositiveSmallIntegerField(default=50, help_text="Pourcentage minimum requis pour le paiement d'avance (1–99 %)", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
            ],
            options={
                'verbose_name': 'Paramètre atelier',
                'verbose_name_plural': 'Paramètres atelier',
                'db_table': 'parametre_atelier',
            },
        ),
    ]
