# Generated by Django 6.0.4 on 2026-06-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sew', '0013_parametre_atelier'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='adresse',
            field=models.TextField(blank=True, help_text='Adresse de livraison par défaut du client', null=True),
        ),
        migrations.AlterField(
            model_name='mesure',
            name='mesures',
            field=models.JSONField(),
        ),
    ]
