# Generated by Django 6.0.4 on 2026-06-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sew', '0014_utilisateur_adresse_alter_mesure_mesures'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='mode_livraison',
            field=models.CharField(choices=[('LIVRAISON', 'Livraison à domicile'), ('RETRAIT', 'Retrait sur place')], default='LIVRAISON', help_text="Livraison par l'atelier, ou retrait par le client / son propre livreur", max_length=20),
        ),
    ]
