# Generated by Django 6.0.4 on 2026-06-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sew', '0015_commande_mode_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='archivee_client',
            field=models.BooleanField(default=False, help_text='Le client a archivé (masqué) cette commande terminée de son espace'),
        ),
    ]
