# Generated by Django 6.0.4 on 2026-06-29 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sew', '0016_commande_archivee_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiau',
            name='couturier',
            field=models.ForeignKey(blank=True, help_text='Couturier propriétaire de ce stock', limit_choices_to={'role': 'COUTURIER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiaux', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modele',
            name='couturier',
            field=models.ForeignKey(blank=True, help_text='Couturier qui a publié ce modèle', limit_choices_to={'role': 'COUTURIER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modeles_publies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materiau',
            name='nom_materiau',
            field=models.CharField(max_length=100),
        ),
    ]
