# Generated by Django 6.0.4 on 2026-06-30 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sew', '0017_materiau_couturier_modele_couturier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_livraison',
            field=models.DateTimeField(blank=True, help_text='Date/heure de livraison effective — départ du délai de recours (72h)', null=True),
        ),
        migrations.CreateModel(
            name='Recours',
            fields=[
                ('id_recours', models.AutoField(primary_key=True, serialize=False)),
                ('motif', models.TextField(help_text='Ce qui ne correspond pas au modèle initial')),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé')], default='OUVERT', max_length=20)),
                ('reponse_couturier', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recours', to='Sew.commande')),
            ],
            options={
                'verbose_name': 'Recours',
                'verbose_name_plural': 'Recours',
                'db_table': 'recours',
                'ordering': ['-date_creation'],
            },
        ),
    ]
