# Generated by Django 6.0.4 on 2026-06-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sew', '0018_commande_date_livraison_recours'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé')], default='CONFIRME', help_text="Un paiement en espèces reste EN_ATTENTE jusqu'à confirmation par l'atelier", max_length=20),
        ),
    ]
